<?php return array(
    'root' => array(
        'pretty_version' => '11.5.x-dev',
        'version' => '11.5.9999999.9999999-dev',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => '35d8ff884e1af68dba05cdddfc2a0aa268ba8d9d',
        'name' => '__root__',
        'dev' => false,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => '11.5.x-dev',
            'version' => '11.5.9999999.9999999-dev',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => '35d8ff884e1af68dba05cdddfc2a0aa268ba8d9d',
            'dev_requirement' => false,
        ),
        'elasticsearch/elasticsearch' => array(
            'pretty_version' => 'v6.8.2',
            'version' => '6.8.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../elasticsearch/elasticsearch',
            'aliases' => array(),
            'reference' => '619c78266999c6e431df9ca0f844e8f656ac145b',
            'dev_requirement' => false,
        ),
        'ezimuel/guzzlestreams' => array(
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezimuel/guzzlestreams',
            'aliases' => array(),
            'reference' => 'abe3791d231167f14eb80d413420d1eab91163a8',
            'dev_requirement' => false,
        ),
        'ezimuel/ringphp' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezimuel/ringphp',
            'aliases' => array(),
            'reference' => '92b8161404ab1ad84059ebed41d9f757e897ce74',
            'dev_requirement' => false,
        ),
        'guzzlehttp/ringphp' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.2.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'dev_requirement' => false,
        ),
        'react/promise' => array(
            'pretty_version' => 'v2.9.0',
            'version' => '2.9.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../react/promise',
            'aliases' => array(),
            'reference' => '234f8fd1023c9158e2314fa9d7d0e6a83db42910',
            'dev_requirement' => false,
        ),
        'ruflin/elastica' => array(
            'pretty_version' => '6.2.1',
            'version' => '6.2.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ruflin/elastica',
            'aliases' => array(),
            'reference' => 'f95cf646f884a8e7b73bd12eda3e5753994b24d3',
            'dev_requirement' => false,
        ),
    ),
);
