name: "Quality Checks"

on:
    push:
    pull_request:
    workflow_dispatch:
    schedule:
        - cron: "30 6 * * 1"

env:
    PHP_EXTENSIONS: "intl, mbstring, json, zip, curl"

jobs:

    php-lint:
        name: "Linting"

        runs-on: "ubuntu-latest"

        strategy:
            matrix:
              include:
                -
                  typo3-version: "^12.4"
                  php-version: "8.1"
                -
                  typo3-version: "^13.4"
                  php-version: "8.2"
                -
                  typo3-version: "^13.4"
                  php-version: "8.3"
                -
                  typo3-version: "^13.4"
                  php-version: "8.4"

        steps:
            -
                name: "Checkout"
                uses: "actions/checkout@v4"
            -
                name: "Setup PHP"
                uses: "shivammathur/setup-php@v2"
                with:
                    php-version: "${{ matrix.php-version }}"
                    extensions: "${{ env.PHP_EXTENSIONS }}"
            -
                name: "Validate composer.json and composer.lock"
                run: "composer validate --strict"
            -
                name: "Determine composer cache directory"
                id: composer-cache
                run: |
                    echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
            -
                name: "Cache dependencies installed with composer"
                uses: "actions/cache@v4"
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: "php-${{ matrix.php-version }}-composer-${{ hashFiles('composer.lock') }}"
                    restore-keys: "php-${{ matrix.php-version }}-composer-"
            -
                name: "Install composer dependencies"
                run: |
                  composer remove --no-update typo3/cms typo3/cms-core
                  composer require typo3/minimal:"${{ matrix.typo3-version }}"
            -
                name: "Run Linter"
                run: "composer lint"

    php-qs:
        name: "PHP QS"

        runs-on: "ubuntu-latest"

        needs: "php-lint"

        strategy:
            matrix:
                command:
                    - "test:phpcs"
                    - "test:rector"
                    - "test:phpcompatibility"
                include:
                  -
                    typo3-version: "^12.4"
                    php-version: "8.1"
                  -
                    typo3-version: "^13.4"
                    php-version: "8.2"
                  -
                    typo3-version: "^13.4"
                    php-version: "8.3"
                  -
                    typo3-version: "^13.4"
                    php-version: "8.4"

        steps:
            -
                name: "Checkout"
                uses: "actions/checkout@v4"
            -
                name: "Setup PHP"
                uses: "shivammathur/setup-php@v2"
                with:
                    php-version: "${{ matrix.php-version }}"
                    extensions: "${{ env.PHP_EXTENSIONS }}"
            -
                name: "Validate composer.json and composer.lock"
                run: "composer validate --strict"
            -
                name: "Determine composer cache directory"
                id: composer-cache
                run: |
                    echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
            -
                name: "Cache dependencies installed with composer"
                uses: "actions/cache@v4"
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: "php-${{ matrix.php-version }}-composer-${{ hashFiles('composer.lock') }}"
                    restore-keys: "php-${{ matrix.php-version }}-composer-"
            -
              name: "Install composer dependencies"
              run: |
                composer remove --no-update typo3/cms typo3/cms-core
                composer require typo3/minimal:"${{ matrix.typo3-version }}"
            -
                name: "Run command"
                run: "composer ${{ matrix.command }}"


    php-stan-unit:
        name: "PHP-Stan-Unit"

        runs-on: "ubuntu-latest"

        needs: ["php-lint", "php-qs"]

        strategy:
            fail-fast: false
            matrix:
                include:
                    -
                        typo3-version: "^12.4"
                        php-version: "8.1"
                    -
                        typo3-version: "^12.4"
                        php-version: "8.2"
                    -
                        typo3-version: "^12.4"
                        php-version: "8.3"
                    -
                        typo3-version: "^12.4"
                        php-version: "8.4"
                    -
                        typo3-version: "^13.4"
                        php-version: "8.2"
                    -
                        typo3-version: "^13.4"
                        php-version: "8.3"
                    -
                        typo3-version: "^13.4"
                        php-version: "8.4"

        steps:
            -
                name: "Checkout"
                uses: "actions/checkout@v4"
            -
                name: "Setup PHP"
                uses: "shivammathur/setup-php@v2"
                with:
                    php-version: "${{ matrix.php-version }}"
                    extensions: "${{ env.PHP_EXTENSIONS }}"
            -
                name: "Validate composer.json and composer.lock"
                run: "composer validate --strict"
            -
                name: "Determine composer cache directory"
                id: composer-cache
                run: |
                    echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
            -
                name: "Cache dependencies installed with composer"
                uses: "actions/cache@v4"
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: "php-${{ matrix.php-version }}-composer-${{ hashFiles('composer.lock') }}"
                    restore-keys: "php-${{ matrix.php-version }}-composer-"
            -
                name: "Install composer dependencies"
                run: |
                    composer remove --no-update typo3/cms typo3/cms-core
                    composer require typo3/minimal:"${{ matrix.typo3-version }}"
            -
                name: "Run PHPStan"
                run: "composer test:phpstan"
            -
                name: "Run PHP unit tests"
                run: "composer test:phpunit"
