name: TER release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    name: TYPO3 TER release

    if: startsWith(github.ref, 'refs/tags/')

    runs-on: ubuntu-20.04

    env:
      TYPO3_API_TOKEN: ${{ secrets.TYPO3_API_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get version
        id: get-version
        run: echo ::set-output name=version::$(echo "${{ github.event.ref }}" | cut -d 'v' -f 2)

      - name: Get comment
        id: get-comment
        run: echo ::set-output name=comment::Released version ${{ steps.get-version.outputs.version }}. Check changelog in documentation on github for more information.

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: intl, mbstring, json, zip, curl

      - name: Install tailor
        run: composer global require typo3/tailor --prefer-dist --no-progress

      - name: Publish to TER
        run: php ~/.composer/vendor/bin/tailor ter:publish --comment "${{ steps.get-comment.outputs.comment }}" ${{ steps.get-version.outputs.version }}
